[package]
name = "machineid-rs"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac = "0.11.0"
sha2 = "0.9.5"

[target.'cfg(windows)'.dependencies]
winreg = "0.9.0"