[package]
name = "machineid-rs"
version = "1.0.2"
edition = "2018"
description = "Get an encrypted HWID/MachineID on windows or linux"
readme="README.md"
repository="https://github.com/Taptiive/machineid-rs"
license = "MIT OR Apache-2.0"
keywords = ["hwid", "machineid", "hardwareid", "machine-id", "hardware-id"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac = "0.11.0"
sha2 = "0.9.5"

[target.'cfg(windows)'.dependencies]
winreg = "0.9.0"